[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/hire-email"
  to = "/?utm_source=email&utm_medium=direct&utm_campaign=job_application&utm_content=recruiter"
  status = 301
  force = true

[[redirects]]
  from = "/hire-linkedin" 
  to = "/?utm_source=linkedin&utm_medium=social&utm_campaign=job_application&utm_content=linkedin_message"
  status = 301
  force = true

[[redirects]]
  from = "/hire-whatsapp"
  to = "/?utm_source=whatsapp&utm_medium=social&utm_campaign=job_application&utm_content=personal_message" 
  status = 301
  force = true